### ISSUE TITLE
Webfact subtheme for specific templates

### ISSUE THREAD

**Issue by Jbartsch** [Boran/webfact-make#1]
Templates such as views-view-field--websites.tpl.php are now copied manually during installation.
A specific subtheme could cover this and further theme related issues.

webfact-make.make:
projects[webfact_theme][type] = "theme"
projects[webfact_theme][subdir] = "custom"
projects[webfact_theme][download][type] = "git"
projects[webfact_theme][download][url] = "git@github.com:Innoveto/webfact_theme.git"

webfact.profile: 
function webfactp_set_theme() {
  $enable = array(
    'theme_default' => 'webfact_theme',
    'admin_theme' => 'seven',
  );

**Comment by Boran** [comment]
agreed, PR merged #2 .

**Comment by Boran** [comment]
I have moved the theme to the Boran account for consistency. The URL syntax in the make file did not work either. Readme in the theme updated too.

**Comment by Boran** [comment]
Theme integrated with fixes, closing issue.
